version: '3.8'
services:
  #Nginx service
  nginx-backend:
    image: nginx
    container_name: prestabanco-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3

  nginx-frontend:
    image: nginx
    container_name: prestabanco-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-frontend-network
    depends_on:
      - react1
      - react2
      - react3

  postgres:
    container_name: prestabanco-postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - prestabanco-postgres-volume:/var/lib/postgresql/data
    networks:
      - prestabanco-backend-network
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
  spring1:
    container_name: prestabanco-backend-container-1
    image: bastianbrito/spring-image
    ports:
      - 8091:8090
    environment:
      DB_HOST: prestabanco-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - prestabanco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: prestabanco-backend-container-2
    image: bastianbrito/spring-image
    ports:
      - 8092:8090
    environment:
      DB_HOST: prestabanco-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - prestabanco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
      
  spring3:
    container_name: prestabanco-backend-container-3
    image: bastianbrito/spring-image
    ports:
      - 8093:8090
    environment:
      DB_HOST: prestabanco-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - prestabanco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: prestabanco-frontend-container-1
    image: bastianbrito/prestabanco-frontend
    networks:
      - prestabanco-frontend-network
    ports:
      - 3001:3000
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  react2:
    container_name: prestabanco-frontend-container-2
    image: bastianbrito/prestabanco-frontend
    networks:
      - prestabanco-frontend-network
    ports:
      - 3002:3000
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: prestabanco-frontend-container-3
    image: bastianbrito/prestabanco-frontend
    ports:
      - 3003:3000
    networks:
      - prestabanco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  prestabanco-postgres-volume:
networks:
  prestabanco-backend-network:
  prestabanco-frontend-network:







